"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Archive, ChevronRight, CircleDollarSign, Dice5, LoaderCircle, Plus, ReceiptText, Trophy, X } from "lucide-react";
import { computeStats, currentStreak } from "@/lib/stats";
import { createNight, loadData, markPaid, multiplyActiveBet, recordGame, saveData } from "@/lib/data/repository";
import { demoData } from "@/lib/data/demo";
import type { Bet, DebtTransaction, Game, NightSetup, Session, TableData } from "@/types";

type View = "table" | "archive" | "tab" | "numbers";
type Sheet = "night" | "winner" | "raise" | "close" | null;
const fmt = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" });

export default function Home() {
  const [data, setData] = useState<TableData | null>(null);
  const [view, setView] = useState<View>("table"); const [sheet, setSheet] = useState<Sheet>(null);
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { loadData().then(setData).catch((e: Error) => setError(e.message)); }, []);
  const update = async (next: TableData) => { setData(next); setSaving(true); setError(""); try { await saveData(next); } catch { setError("La mesa no pudo guardar eso. Intenta otra vez antes de que cambie la versión de la historia."); } finally { setSaving(false); } };
  if (!data) return <main className="loading"><LoaderCircle aria-label="Cargando registros" /> <span>Abriendo el libro de la mesa…</span></main>;
  const open = data.sessions.find((s) => !s.endedAt) ?? data.sessions[0]; const stats = computeStats(data);
  return <main className="shell">
    <header className="masthead"><div><p className="kicker">Official records of questionable decisions</p><h1>THE TABLE</h1></div><div className="sync" aria-live="polite">{saving ? "guardando" : error ? "error" : "en mesa"}</div></header>
    {error && <div role="alert" className="error"><span>{error}</span><button onClick={() => setError("")} aria-label="Cerrar error"><X size={18}/></button></div>}
    {view === "table" && <TableView data={data} active={open} stats={stats} onNew={() => setSheet("night")} onSheet={setSheet} onDemo={() => update(demoData())} />}
    {view === "archive" && <ArchiveView data={data} />}
    {view === "tab" && <TabView data={data} onPaid={(id) => update(markPaid(data, id))} />}
    {view === "numbers" && <NumbersView stats={stats} />}
    <nav aria-label="Navegación principal" className="rail"><NavIcon label="Table" active={view === "table"} onClick={() => setView("table")} icon={<Dice5/>}/><NavIcon label="Archive" active={view === "archive"} onClick={() => setView("archive")} icon={<Archive/>}/><NavIcon label="The Tab" active={view === "tab"} onClick={() => setView("tab")} icon={<ReceiptText/>}/><NavIcon label="Numbers" active={view === "numbers"} onClick={() => setView("numbers")} icon={<Trophy/>}/></nav>
    {sheet === "night" && <NightSheet onClose={() => setSheet(null)} onCreate={(venue, amount, setup) => { update(createNight(data, venue, amount, setup)); setSheet(null); }} />}
    {sheet === "winner" && open && (
      <WinnerSheet sides={sidesFor(data, open)} onClose={() => setSheet(null)} onWinner={(winner, loser, settle) => { update(recordGame(data, open.id, winner, loser, settle)); setSheet(null); }} hasBet={Boolean(data.bets.find((b) => b.sessionId === open.id && b.status === "OPEN"))} />
    )}
    {sheet === "raise" && open && <RaiseSheet active={data.bets.find((b) => b.sessionId === open.id && b.status === "OPEN")} onClose={() => setSheet(null)} onRaise={(m) => { try { update(multiplyActiveBet(data, open.id, m)); setSheet(null); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cambiar la apuesta."); } }} />}
    {sheet === "close" && open && <CloseSheet active={data.bets.find((b) => b.sessionId === open.id && b.status === "OPEN")} onClose={() => setSheet(null)} onConfirm={() => setSheet("winner")} />}
  </main>;
}

function TableView({ data, active, stats, onNew, onSheet, onDemo }: { data: TableData; active?: Session; stats: ReturnType<typeof computeStats>; onNew: () => void; onSheet: (s: Sheet) => void; onDemo: () => void }) {
  if (!active) return <section className="clean-state"><p className="kicker">JUANSE VS TOMMY</p><CupRack/><h2>THE TABLE<br/>IS CLEAN.</h2><p>Por ahora.</p><div className="empty-score"><b>0</b><span>—</span><b>0</b></div><button className="primary massive" onClick={onNew}><Plus/> Empezar la primera noche</button><button className="quiet" onClick={onDemo}>Cargar una noche de ejemplo</button></section>;
  const sides = sidesFor(data, active); const games = data.games.filter((g) => g.sessionId === active.id); const score = scoreOf(games, sides); const streak = currentStreak(games);
  const activeBet = data.bets.find((b) => b.sessionId === active.id && b.status === "OPEN");
  return <section className="table-view"><div className="night-line"><span>{fmt.format(new Date(active.date + "T12:00:00"))} · {active.venue} · {active.mode === "2v2" ? "2v2" : "1v1"}</span><button className="quiet compact" onClick={onNew}>Nueva noche <Plus size={15}/></button></div><ScoreBoard left={score.a} right={score.b} leftLabel={sides.a.label} rightLabel={sides.b.label} label="ESTA NOCHE"/><p className="streak" aria-live="polite">{streak ? <><b>{sideFor(streak.playerId, sides) === "a" ? sides.a.label : sides.b.label}</b> <span>{Array.from({length: Math.min(streak.count, 5)}).map(() => "W").join(" ")}</span> <em>racha de {streak.count}</em></> : "La primera versión de la historia empieza aquí."}</p>{activeBet ? <BetBoard bet={activeBet} /> : <div className="bet-board quiet-board"><span>No hay apuesta activa.</span><button onClick={onNew}>Abrir otra mesa</button></div>}<div className="actions"><button className="primary record" onClick={() => onSheet("winner")}><Trophy/> Registrar partida</button>{activeBet && <><button className="accent" onClick={() => onSheet("raise")}>Doble / triple <ChevronRight size={19}/></button><button className="outline" onClick={() => onSheet("close")}>Cobrar / cerrar deuda</button></>}</div><aside className="rivalry-note"><span>{active.mode === "2v2" ? "ESTA MESA" : "ALL TIME"}</span><b>{score.a} — {score.b}</b><p>{active.mode === "2v2" ? "Cuatro personas. La misma falta de criterio." : stats.leader ? `${stats.leader.name} lidera por ${stats.leader.margin}.` : "Ni la mesa puede separar esto."}</p></aside></section>;
}
function ScoreBoard({ left, right, leftLabel = "JUANSE", rightLabel = "TOMMY", label }: { left: number; right: number; leftLabel?: string; rightLabel?: string; label: string }) { return <section className="scoreboard" aria-label={`Marcador: ${leftLabel} ${left}, ${rightLabel} ${right}`}><p>{label}</p><div><span>{leftLabel.toUpperCase()}</span><strong>{left}</strong><i>—</i><strong>{right}</strong><span>{rightLabel.toUpperCase()}</span></div></section>; }
function BetBoard({ bet }: { bet: Bet }) { return <section className="bet-board"><div className="bet-head"><span>EN JUEGO</span><span>{bet.currentAmount > bet.initialAmount ? "MULTIPLICADO" : "APUESTA BASE"}</span></div><strong>{bet.currentAmount}<small> SHOTS</small></strong><p>{bet.currentAmount > bet.initialAmount ? `De ${bet.initialAmount} a ${bet.currentAmount}. La mesa tomó nota.` : "Una partida decide quién se va con la cuenta."}</p><CupRack className="bet-cups" label="Diez vasos en formación" /></section>; }
function CupRack({ className = "", label }: { className?: string; label?: string }) { return <div className={`cup-rack ${className}`} aria-label={label} aria-hidden={!label}>{Array.from({ length: 10 }).map((_, i) => <i key={i}/>)}</div>; }

function ArchiveView({ data }: { data: TableData }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  return <section className="archive"><p className="kicker">THE ARCHIVE</p><h2>NOCHES<br/>QUE LA MESA RECUERDA.</h2>{data.sessions.length === 0 ? <p className="archive-empty">Todavía no hay nada que negar.</p> : data.sessions.map((session) => {
    const sides = sidesFor(data, session); const games = data.games.filter((g) => g.sessionId === session.id); const score = scoreOf(games, sides); const bet = data.bets.filter((b) => b.sessionId === session.id).at(-1); const events = data.betEvents.filter((e) => data.bets.some((b) => b.id === e.betId && b.sessionId === session.id));
    return <article className="archive-entry" key={session.id}><div className="date-stamp">{fmt.format(new Date(session.date + "T12:00:00"))}</div><div><p>{session.venue} · {session.mode === "2v2" ? "2v2" : "1v1"}</p><h3>{sides.a.label} {score.a} <i>—</i> {score.b} {sides.b.label}</h3><small>{bet ? `${bet.currentAmount} shots estuvieron en juego` : "Solo orgullo, por suerte"}</small><button className="archive-toggle" onClick={() => setExpanded(expanded === session.id ? null : session.id)}>{expanded === session.id ? "Cerrar registro" : "Ver la noche →"}</button>{expanded === session.id && <ol className="timeline">{[...games.map((game) => ({ at: game.createdAt, label: `${sideFor(game.winnerId, sides) === "a" ? sides.a.label : sides.b.label} gana`, detail: "partida registrada" })), ...events.map((event) => ({ at: event.createdAt, label: event.type === "INITIAL" ? "Apuesta inicial" : event.type === "SETTLED" ? "Deuda cerrada" : event.type === "DOUBLE_OR_NOTHING" ? "Doble o nada" : event.type === "TRIPLE_OR_NOTHING" ? "Triple o nada" : "Apuesta ajustada", detail: `${event.amountBefore} → ${event.amountAfter} shots` }))].sort((a,b) => a.at.localeCompare(b.at)).map((entry, i) => <li key={`${entry.at}-${i}`}><time>{new Date(entry.at).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}</time><span><b>{entry.label}</b><small>{entry.detail}</small></span></li>)}</ol>}</div></article>;
  })}</section>;
}
function TabView({ data, onPaid }: { data: TableData; onPaid: (id: string) => void }) { const open = data.debtTransactions.filter((d) => d.status === "OPEN"); const paid = data.debtTransactions.filter((d) => d.status === "PAID"); const lead = open[0]; return <section className="tab-view"><p className="kicker">THE TAB</p><h2>BALANCE<br/>ACTUAL</h2><div className="balance"><strong>{lead?.amount ?? 0}</strong><span>SHOTS</span><p>{lead ? `${playerName(data, lead.debtorPlayerId)} debe a ${playerName(data, lead.creditorPlayerId)}.` : "Milagrosamente estamos a paz y salvo."}</p></div><h3>CUENTA PENDIENTE</h3>{open.length ? open.map((debt) => <DebtLine data={data} debt={debt} key={debt.id} action={() => onPaid(debt.id)}/>) : <p className="ledger-empty">Nada pendiente. Algo sospechoso pasó.</p>} {paid.length > 0 && <><h3 className="paid-heading">YA PAGADO</h3>{paid.map((debt) => <DebtLine data={data} debt={debt} key={debt.id}/>)}</>}</section>; }
function DebtLine({ data, debt, action }: { data: TableData; debt: DebtTransaction; action?: () => void }) { return <article className="debt-line"><div><b>{playerName(data, debt.debtorPlayerId)} <span>→</span> {playerName(data, debt.creditorPlayerId)}</b><small>{debt.amount} shots · {debt.status === "PAID" ? "pagado" : "deuda oficialmente reconocida"}</small></div>{action && <button className="outline small" onClick={action}>Pagado</button>}</article>; }
function NumbersView({ stats }: { stats: ReturnType<typeof computeStats> }) { return <section className="numbers"><p className="kicker">THE NUMBERS</p><h2>ESTADÍSTICAS<br/>INNECESARIAMENTE SERIAS.</h2><ScoreBoard left={stats.juanseWins} right={stats.tommyWins} leftLabel={stats.juanseName} rightLabel={stats.tommyName} label="HEAD TO HEAD · ALL TIME"/><div className="split-stat"><span><b>{stats.juanseRate}%</b> win rate {stats.juanseName}</span><span><b>{stats.tommyRate}%</b> win rate {stats.tommyName}</span></div><RivalryCharts stats={stats} /><section className="bad-index"><p>BAD DECISIONS INDEX</p><strong>{stats.badIndex}<small> / 100</small></strong><span>{stats.badCopy}</span><small>8 puntos por multiplicador + 1 por cada shot añadido a la apuesta. Sin IA. Sin excusas.</small></section><dl className="stat-list"><div><dt>Partidas totales</dt><dd>{stats.totalGames}</dd></div><div><dt>Racha máxima</dt><dd>{stats.juanseName} {stats.juanseMaxStreak} · {stats.tommyName} {stats.tommyMaxStreak}</dd></div><div><dt>Noches ganadas</dt><dd>{stats.juanseName} {stats.juanseNights} · {stats.tommyName} {stats.tommyNights}</dd></div><div><dt>Mayor deuda</dt><dd>{stats.maxDebt} shots</dd></div><div><dt>Doble o nada</dt><dd>{stats.doubles}</dd></div><div><dt>Triple o nada</dt><dd>{stats.triples}</dd></div><div><dt>Shots pagados</dt><dd>{stats.shotsPaid}</dd></div></dl></section>; }
function RivalryCharts({ stats }: { stats: ReturnType<typeof computeStats> }) {
  const games = stats.juanseWins + stats.tommyWins; const width = 280; const baseline = 42; let lead = 0;
  const values = [0, ...stats.recentRivalry.map((winner) => { lead += winner === "juanse" ? 1 : -1; return lead; })]; const bound = Math.max(2, ...values.map((value) => Math.abs(value))); const path = values.map((value, index) => `${index ? "L" : "M"}${16 + (index / Math.max(1, values.length - 1)) * (width - 32)} ${baseline - (value / bound) * 27}`).join(" ");
  return <section className="charts" aria-label="Gráficos de la rivalidad"><figure className="chart"><figcaption>QUIÉN HA GANADO MÁS</figcaption>{games ? <><div className="bar-labels"><span>{stats.juanseName}</span><b>{stats.juanseWins}</b><b>{stats.tommyWins}</b><span>{stats.tommyName}</span></div><div className="win-bar"><i style={{ width: `${stats.juanseRate}%` }} /><i style={{ width: `${stats.tommyRate}%` }} /></div></> : <p>Primero hay que jugar. Obvio.</p>}</figure><figure className="chart"><figcaption>FORMA · ÚLTIMAS {stats.recentRivalry.length || 0}</figcaption>{stats.recentRivalry.length ? <><svg viewBox="0 0 280 84" role="img" aria-label="Evolución del margen en las últimas partidas"><path className="axis" d="M16 42H264"/><path className="form-line" d={path}/>{values.map((value, index) => <circle key={index} className={value >= 0 ? "juanse-dot" : "tommy-dot"} cx={16 + (index / Math.max(1, values.length - 1)) * (width - 32)} cy={baseline - (value / bound) * 27} r="3"/>)}</svg><div className="form-legend"><span>{stats.juanseName} arriba</span><span>{stats.tommyName} arriba</span></div></> : <p>La gráfica todavía está sobria.</p>}</figure></section>;
}

function Sheet({ children, onClose }: { children: ReactNode; onClose: () => void }) { return <div className="sheet-backdrop" role="presentation"><section className="sheet" role="dialog" aria-modal="true"><button className="close" onClick={onClose} aria-label="Cerrar"><X/></button>{children}</section></div>; }
function NightSheet({ onClose, onCreate }: { onClose: () => void; onCreate: (venue: string, amount: number, setup: NightSetup) => void }) {
  const [venue, setVenue] = useState("Shot Me"); const [amount, setAmount] = useState("10"); const [mode, setMode] = useState<"1v1" | "2v2">("1v1");
  const [names, setNames] = useState({ a1: "Juanse", a2: "", b1: "Tommy", b2: "" });
  const setName = (key: keyof typeof names, name: string) => setNames({ ...names, [key]: name });
  const setup: NightSetup = { mode, teamA: [{ id: "juanse", name: names.a1 }, ...(mode === "2v2" ? [{ id: "team-a-2", name: names.a2 }] : [])], teamB: [{ id: "tommy", name: names.b1 }, ...(mode === "2v2" ? [{ id: "team-b-2", name: names.b2 }] : [])] };
  const ready = Number(amount) > 0 && setup.teamA.every((player) => player.name.trim()) && setup.teamB.every((player) => player.name.trim());
  return <Sheet onClose={onClose}><p className="kicker">NUEVA NOCHE · 1 DE 2</p><h2>ARMA<br/>LA MESA.</h2><div className="mode-picker" role="group" aria-label="Formato de juego"><button className={mode === "1v1" ? "selected" : ""} onClick={() => setMode("1v1")}>1 VS 1<small>clásico</small></button><button className={mode === "2v2" ? "selected" : ""} onClick={() => setMode("2v2")}>2 VS 2<small>cuatro culpables</small></button></div><div className="lineup"><p>Equipo A</p><label>Jugador 1<input value={names.a1} onChange={(e) => setName("a1", e.target.value)} autoFocus/></label>{mode === "2v2" && <label>Jugador 2<input value={names.a2} onChange={(e) => setName("a2", e.target.value)} placeholder="Nombre"/></label>}<p>Equipo B</p><label>Jugador 1<input value={names.b1} onChange={(e) => setName("b1", e.target.value)}/></label>{mode === "2v2" && <label>Jugador 2<input value={names.b2} onChange={(e) => setName("b2", e.target.value)} placeholder="Nombre"/></label>}</div><label>Lugar<input value={venue} onChange={(e) => setVenue(e.target.value)}/></label><label>Shots en juego<input inputMode="numeric" type="number" min="1" value={amount} onChange={(e) => setAmount(e.target.value)}/></label><p className="hint">Los nombres quedan guardados para el historial. La deuda se asigna al primer jugador de cada equipo; es el portavoz financiero por ahora.</p><button className="primary massive" disabled={!ready} onClick={() => onCreate(venue, Number(amount), setup)}>Poner la mesa</button></Sheet>;
}
function WinnerSheet({ sides, onClose, onWinner, hasBet }: { sides: Sides; onClose: () => void; onWinner: (winner: string, loser: string, settle: boolean) => void; hasBet: boolean }) { const [winner, setWinner] = useState<"a" | "b" | null>(null); const chosen = winner === "a" ? sides.a : winner === "b" ? sides.b : null; const loser = winner === "a" ? sides.b : sides.a; return <Sheet onClose={onClose}><p className="kicker">REGISTRAR PARTIDA · 2 DE 2</p><h2>¿QUIÉN SE LA<br/>LLEVÓ?</h2><div className="winner-buttons"><button onClick={() => setWinner("a")} className={winner === "a" ? "selected" : ""}>{sides.a.label}</button><span>vs</span><button onClick={() => setWinner("b")} className={winner === "b" ? "selected" : ""}>{sides.b.label}</button></div>{chosen && <><p className="hint">{hasBet ? "¿Esta fue la partida que cierra la apuesta?" : "El marcador se actualiza en silencio."}</p><button className="primary massive" onClick={() => onWinner(chosen.id, loser.id, hasBet)}>{hasBet ? "Registrar y cerrar apuesta" : "Registrar partida"}</button>{hasBet && <button className="outline full" onClick={() => onWinner(chosen.id, loser.id, false)}>Solo sumar al marcador</button>}</>}</Sheet>; }
function RaiseSheet({ active, onClose, onRaise }: { active?: Bet; onClose: () => void; onRaise: (m: number) => void }) { const [custom, setCustom] = useState("1.5"); if (!active) return null; return <Sheet onClose={onClose}><p className="kicker">SUBIR LA APUESTA</p><h2>DOBLE O<br/>NADA?</h2><div className="raise-preview"><b>{active.currentAmount}</b><span>→</span><b>{active.currentAmount * 2}</b><small>shots · una partida decide la salida</small></div><button className="primary massive" onClick={() => onRaise(2)}>Nos hacemos responsables · x2</button><button className="accent full" onClick={() => onRaise(3)}>Esto escala rápido · x3</button><label>Multiplicador personalizado<input inputMode="decimal" value={custom} onChange={(e) => setCustom(e.target.value)}/></label><button className="outline full" onClick={() => onRaise(Number(custom))}>Aplicar x{custom}</button><button className="quiet full" onClick={onClose}>Todavía tenemos criterio</button></Sheet>; }
function CloseSheet({ active, onClose, onConfirm }: { active?: Bet; onClose: () => void; onConfirm: () => void }) { if (!active) return null; return <Sheet onClose={onClose}><p className="kicker">CERRAR APUESTA</p><h2>{active.currentAmount} SHOTS<br/>EN LA LÍNEA.</h2><p className="hint">Registra la partida decisiva. Quien pierda queda con la deuda; no se acumula otra cuenta.</p><button className="primary massive" onClick={onConfirm}><CircleDollarSign/> Registrar resultado final</button></Sheet>; }
function NavIcon({ label, active, onClick, icon }: { label: string; active: boolean; onClick: () => void; icon: ReactNode }) { return <button className={active ? "active" : ""} onClick={onClick}>{icon}<span>{label}</span></button>; }
type Sides = { a: { id: string; label: string; memberIds: string[] }; b: { id: string; label: string; memberIds: string[] } };
function playerName(data: TableData, id: string) { return data.players.find((player) => player.id === id)?.name ?? id; }
function sidesFor(data: TableData, session: Session): Sides { const a = session.teamAPlayerIds?.length ? session.teamAPlayerIds : ["juanse"]; const b = session.teamBPlayerIds?.length ? session.teamBPlayerIds : ["tommy"]; return { a: { id: a[0], memberIds: a, label: a.map((id) => playerName(data, id)).join(" + ") }, b: { id: b[0], memberIds: b, label: b.map((id) => playerName(data, id)).join(" + ") } }; }
function sideFor(id: string, sides: Sides) { return sides.a.memberIds.includes(id) ? "a" : "b"; }
function scoreOf(games: Game[], sides: Sides) { return { a: games.filter((game) => sideFor(game.winnerId, sides) === "a").length, b: games.filter((game) => sideFor(game.winnerId, sides) === "b").length }; }
